jobs:
  - name: shippable_runCI
    type: runCI
    steps:
      - IN: nightly-trigger
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
  - name: shippable_runSh
    type: runSh
    steps:
      - IN: nightly-trigger
      - TASK:
        - script: echo 'test script'