jobs:
  - name: shippable_runCI
    type: runCI
    steps:
      - IN: shippable_ciRepo
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
  - name: shippable_runSh
    type: runSh
    steps:
      - IN: repo-trigger
        switch: off
      - IN: hourly-trigger
      - TASK:
        - script: ./IN/repo-trigger/gitRepo/test.sh
    on_failure:
      - script: echo "AUTOMATION FAILED"
      - NOTIFY: email-notification
      - NOTIFY: slack-notification