jobs:
  - name: shippable_runCI
    type: runCI
    steps:
      - IN: shippable_ciRepo
    on_success:
      - NOTIFY: slack-notification
    on_failure:
      - NOTIFY: slack-notification
  - name: automation_runSh
    type: runSh
    steps:
      - IN: repo-trigger
        switch: off
      - IN: hourly-trigger
      - TASK:
        - script: ./IN/repo-trigger/gitRepo/test.sh
    on_success:
      - NOTIFY: slack-notification
    on_failure:
      - NOTIFY: slack-notification
